# Generated by Django 4.0.4 on 2022-04-19 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_attempts', models.PositiveIntegerField(blank=True, default=0)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4)),
                ('transaction_id', models.CharField(blank=True, max_length=250, null=True)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
