# Generated by Django 4.0.4 on 2022-05-12 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingitem',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='billingitem',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='billingitem',
            name='validation_attempts',
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
