# Generated by Django 4.0.4 on 2022-05-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_billingitem_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
