# Generated by Django 4.0.4 on 2022-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billingitem_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deposit'), (2, 'Charge'), (3, 'Block'), (4, 'Finished')], null=True),
        ),
    ]
